export const Category = {
	ScriptTypes: 'Script Types',
	Types: 'Types',
	Annotations: 'Annotations',
	Keywords: 'Keywords',
	Operators: 'Operators',
	BarData: 'Bar Data',
	Colors: 'Colors',
	Strings: 'Strings',
	Maths: 'Maths',
	Maps: 'Maps',
	Arrays: 'Arrays',
	Matrixes: 'Matrixes',
	BarState: 'Bar State',
	ChartTypesPoints: 'Chart Types & Points',
	Currency: 'Currency',
	Datetime: 'Datetime',
	Plotting: 'Plotting',
	Indicators: 'Indicators',
	Inputs: 'Inputs',
	Labels: 'Labels',
	Lines: 'Lines',
	Boxes: 'Boxes',
	Polylines: 'Polylines',
	Alerts: 'Alerts',
	Syminfo: 'Symbol Info',
	Requests: 'Requests',
	Sessions: 'Sessions',
	Timeframe: 'Timeframe',
	Strategy: 'Strategy',
	Tables: 'Tables',
	LoggingDebugging: 'Logging & Debugging',
	TextsFormatting: 'Texts & Formatting',
	PositionsLocations: 'Positions & Locations',
	StylingLayout: 'Styling & Layout',
};

export const CATEGORY_COLUMNS = {
	[Category.ScriptTypes]: 0,
	[Category.Types]: 0,
	[Category.Operators]: 0,
	[Category.Plotting]: 0,
	[Category.BarState]: 0,
	[Category.Inputs]: 0,
	[Category.Strings]: 0,
	[Category.Maths]: 0,
	[Category.Indicators]: 0,
	[Category.Sessions]: 0,
	[Category.Timeframe]: 2,
	[Category.Tables]: 1,
	[Category.Alerts]: 2,
	[Category.Polylines]: 1,
	[Category.Annotations]: 1,
	[Category.BarData]: 1,
	[Category.Boxes]: 0,
	[Category.Datetime]: 1,
	[Category.Labels]: 1,
	[Category.Lines]: 1,
	[Category.Maps]: 1,
	[Category.Arrays]: 1,
	[Category.Matrixes]: 1,
	[Category.Keywords]: 2,
	[Category.Colors]: 2,
	[Category.ChartTypesPoints]: 2,
	[Category.Syminfo]: 2,
	[Category.Requests]: 2,
	[Category.Strategy]: 2,
	[Category.Currency]: 2,
	[Category.LoggingDebugging]: 0,
	[Category.TextsFormatting]: 0,
	[Category.PositionsLocations]: 2,
	[Category.StylingLayout]: 2,
};

export const NUMBER_OF_COLUMNS = Math.max(...Object.values(CATEGORY_COLUMNS)) + 1;
